### ISSUE TITLE
Need installation README

### ISSUE THREAD

**Issue by RoiArthurB** [WARMTeam/HoanKiemAir_Android#1]
As this project may be installed by plenty of different people (with diverse knowledge), it's important to add a step-by-step installation process.

This information (to be easily found) could fit in the current empty README.

**Comment by hu1909** [comment]
I have just added README for installing HoanKiem Air

**Comment by RoiArthurB** [comment]
So far it's pretty empty... 🧐
![image](https://user-images.githubusercontent.com/16764085/173030460-6b196ebb-b577-4910-81d3-630fdbbc5157.png)

Also, I think it'll be better in the root of the repository to avoid having to search for it and, maybe, easily turn it into website with Github Pages :)

**Comment by hu1909** [comment]
Oh, this one I forgot to delete. My Idea is that I just explain how to install everything in the root of the repository so It's easier to follow
