### ISSUE TITLE
GAMA freeze if too many Android requests

### ISSUE THREAD

**Issue by RoiArthurB** [WARMTeam/HoanKiemAir_Android#2]
For some unknown reason (didn't dig it enough), but GAMA is freezing after some times changing parameters with the android application.

From what we explored: 
- it's not coming from the console over-charged of data (even if, this can lead to some performance leak too); we did comment the `write` commands unsuccessfully
- it's not happening if not using the app (so it's not a model flaw)
- If waiting long enough, GAMA will work back after some times (may be the time to empty some command stack? 🤷🤷🤷)

**Comment by hu1909** [comment]
About this issue, I try many times in my laptop, it totally worked well, it was not freeze and did not crashed. When I tried in my laptop, I could clearly see that the rate of pollution increase quite stable and slower which differ a lot with PC we have. 
So may be I think when Patrick change some parameter , it was impact on GAMA model.

**Comment by RoiArthurB** [comment]
Did you tried to use this _buggy_ model on your computer to see if the behavior seems to come from the model or the computer ? Also, what OS do you use on your laptop ? 🤔🤔

**Comment by hu1909** [comment]
I have already ran this buggy model in my computer, it seem like the problem from the model, it is also freeze in my computer.

**Comment by hu1909** [comment]
I will close this issue because this issue relate to re-connecting issue. So when I fix that, this issue's also fixed
