### ISSUE TITLE
More easily re-connecting to GAMA

### ISSUE THREAD

**Issue by RoiArthurB** [WARMTeam/HoanKiemAir_Android#3]
As the GAML model have several experiments, it happened that we switched from one experiment to another.

This operation can't be done from the application, but to reconnect the application to the newly opened experiment, it requires closing the app and re-open it to reconnect it.

**Expected behavior**

Either :
- As the application knows the correct IP, it could try to automatically re-connect to the computer (with a delay of a few seconds) if the app did previously successfully connect to GAMA
- Having a button to manually reconnect to GAMA with the same settings as the currently used in the app
- Both of the 2 above propositions

**Comment by hu1909** [comment]
I am just successful in creating re-connect with my App, I use the second option to do that which is having a button to manually reconnect to GAMA
