### ISSUE TITLE
Go back to previous activity in Android 

### ISSUE THREAD

**Issue by hu1909** [WARMTeam/HoanKiemAir_Android#8]
About the Chart, When we go back to ConnectActivity and try to connect again to GAMA, the Line Chart is not responding anymore which is the same as when we close the GAMA model.  When we do not have anything to handle that so the GAMA model turn off, the mobile app won't turn off as well 

There are 2 options that we have : 
  <ul>
     <li> Try to catch the exception when we go back to ConnectActivity, maybe when we go back, it pops up the same exception that when we close the GAMA model </li>
     <li> Or try to make user can not go back to previous activity </li>
</ul>

**Comment by RoiArthurB** [comment]
The application aims to be left open to any visitors in exposition place. This means that the application should (1) be as natural to use as possible (no explanation, no long time to understand its usage, not for IT people only), and (2) needs as little maintenance as possible (the best being no maintenance at all).

Then I'd prefer the first option of catching the exception and, in the popup, proposition an auto-reconnect button :)

**Comment by hu1909** [comment]
Thank you, Arthur, I will follow the first option.

**Comment by hu1909** [comment]
I just write some code to handle this, and It finally works.

**Comment by RoiArthurB** [comment]
Congrats :wink:
