### ISSUE TITLE
Keep the latest IP address saved

### ISSUE THREAD

**Issue by RoiArthurB** [WARMTeam/HoanKiemAir_Android#9]
I'm not sure if it's the case already, feel free to close it if not relevant.

Would be great that the app save (in application storage, to keep the information over application's restart) the latest IP address used with the app. This will ease the connection and re-connection of the application with GAMA in a single exposition site over days.

**Comment by hu1909** [comment]
I just create a save IP address =), everything work well so a new enhancement is added
